[package]
name = "functios_2"
version = "0.1.0"
authors = ["x332 <kinspotting@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
